### PR TITLE
An early version of the formatter impl

### PR DESCRIPTION
**Pull request by meysholdt**
this
- enables the formatter
- implements formatting for 
  - (grouped) parenthesis, braces and backets
  - semicolon insertion
- adds an Xpect test method to test the formatter
- adds tests for the formatting features mentioned above
- adds an example for autowrap
- adds an example for preference values

### CODE REVIEW

**Comment by JensN4** [comment]
Just a comment: I haven't changed the NO_LINE_TERMINATOR rule, since this would not be easily possible. See remark in meeting minutes or IDE-2233.

**Comment by meysholdt** [comment]
Thank you!

**Comment by yoosiba** [comment]
@meysholdt @JensN4  @torstenkraemer formatting tests fail on windows. On Jenkins I saw issues with `formatter2/autowrap.n4js.xt` and `formatter2/braces.n4js.xt`. 
Anyone wants to look into that?

**Comment by JensN4** [comment]
@torstenkraemer Could you have a look at that?

**Comment by torstenkraemer** [comment]
I will look into this.

**Pull request merged**
